version: '3.1'

services:
  postgresdb:
    image: postgres:11
    command:
      [
        "postgres",
        "-c", "log_statement=all",
        "-c", "log_destination=stderr",
        "-c", "log_line_prefix=",
        "-c", "log_statement=mod"
      ]
    container_name: postgresdb
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: moviedb
      POSTGRES_PASSWORD: moviedb
    ports:
      - "5432:5432"