version: '3.8'

# log reference : https://www.postgresql.org/docs/current/runtime-config-logging.html
# https://postgresqlco.nf/doc/en/param/log_statement/
services:
  postgresdb:
    image: postgres:11
    command:
      [
        "postgres",
        "-c", "log_statement=ddl",
        "-c", "log_line_prefix=",
        "-c", "log_statement=mod",
      ]
    container_name: the_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"