version: '3.1'

# log reference : https://www.postgresql.org/docs/current/runtime-config-logging.html
# https://postgresqlco.nf/doc/en/param/log_statement/
services:
  postgresdb:
    image: postgres:11
    command:
      [
        "postgres",
        "-c", "log_statement=ddl",
        "-c", "log_line_prefix=",
        "-c", "log_statement=mod",
      ]
    container_name: postgresdb
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: moviedb
      POSTGRES_PASSWORD: moviedb
    ports:
      - "5432:5432"