version: '3.1'

# log reference : https://www.postgresql.org/docs/current/runtime-config-logging.html
services:
  postgresdb:
    image: postgres:11
    command:
      [
        "postgres",
        "-c", "log_statement=ddl",
        "-c", "log_destination=stderr",
        "-c", "log_line_prefix=",
        "-c", "log_statement=mod",
        "-c", "log_min_duration_statement=-1",
        "-c", "log_checkpoints=off",             # Reduce noise in logs
        "-c", "log_connections=off",             # Reduce noise in logs
        "-c", "log_disconnections=off",
      ]
    container_name: postgresdb
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: moviedb
      POSTGRES_PASSWORD: moviedb
    ports:
      - "5432:5432"